
services:
  test_db:
    container_name: test_db
    platform: linux/amd64
    image: mysql:8.0.28
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_USER=test_db
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_PASSWORD=123
    ports:
      - 3281:3306
    volumes:
      - ./test_db/_docker/data/mysql:/var/lib/mysql
      - ./test_db/_docker/config/mysql/privileges.sql:/docker-entrypoint-initdb.d/privileges.sql
    healthcheck:
      test: [ "CMD-SHELL", 'mysqladmin ping' ]
      interval: 10s
      timeout: 2s
      retries: 10
